### ISSUE TITLE
Corrigir CPF com o números de 0 a 9 nos onze dígitos 

### ISSUE THREAD

**Issue by felixltda** [alvarofpp/validate-docbr#11]
O CPF 000.000.000-00 até o 999.999.999-99 atende todos os parâmetros do algoritmo, mas não são CPF válidos. Está retornado True.

**Comment by alvarofpp** [comment]
Os CPFs de 000.000.000-00 até 999.999.999-99 foram considerados como válidos pois, em alguns casos, existem pessoas vinculadas a eles. Usei a base de dados da [Coleção de CNPJs e CPFs brasileiros do Brasil.IO](https://brasil.io/dataset/documentos-brasil/documents) para verificar esses documentos:

| CPF | Pessoa | Consulta |
| --- | ------ | -------- |
| 000.000.000-00 | - | `https://brasil.io/dataset/documentos-brasil/documents?search=00000000000&document_type=CPF&document=&name=&sources=` |
| 111.111.111-11 | AKA CENTRAL PARK - NEW YORK | `https://brasil.io/dataset/documentos-brasil/documents?search=11111111111&document_type=CPF&document=&name=&sources=` |
| 222.222.222-22 | - | `https://brasil.io/dataset/documentos-brasil/documents?search=22222222222&document_type=CPF&document=&name=&sources=` |
| 333.333.333-33 | - | `https://brasil.io/dataset/documentos-brasil/documents?search=33333333333&document_type=CPF&document=&name=&sources=` |
| 444.444.444-44 | - | `https://brasil.io/dataset/documentos-brasil/documents?search=44444444444&document_type=CPF&document=&name=&sources=` |
| 555.555.555-55 | ISAEL HERMINIO DA SILVA | `https://brasil.io/dataset/documentos-brasil/documents?search=55555555555&document_type=CPF&document=&name=&sources=` |
| 666.666.666-66 | - | `https://brasil.io/dataset/documentos-brasil/documents?search=66666666666&document_type=CPF&document=&name=&sources=` |
| 777.777.777-77 | ANTONIO GONÇALO DA SILVA | `https://brasil.io/dataset/documentos-brasil/documents?search=77777777777&document_type=CPF&document=&name=&sources=` |
| 888.888.888-88 | - | `https://brasil.io/dataset/documentos-brasil/documents?search=88888888888&document_type=CPF&document=&name=&sources=` |
| 999.999.999-99 | JOAQUIM ROCHA MATOS | `https://brasil.io/dataset/documentos-brasil/documents?search=99999999999&document_type=CPF&document=&name=&sources=` |

**Comment by alvarofpp** [comment]
Porém, é comum as pessoas desconsiderarem esses CPFs. Creio que a alternativa para esse problema seria adicionar uma flag, que iria indicar se o desenvolvedor quer ou não considerar essas entradas.

**Comment by alvarofpp** [comment]
> O CPF 000.000.000-00 até o 999.999.999-99 atende todos os parâmetros do algoritmo, mas não são CPF válidos. Está retornado True.

Foi adicionado o parâmetro `repeated_digits` no construtor da classe CPF (`False` por padrão), como a existência de uma variável de mesmo nome que indique se você quer ou não deixar como válido os CPFs de 000.000.000-00 até 999.999.999-99 (`False` indica que são inválidos, `True` indica que são válidos).

Coloquei esse caso especial na documentação, está na parte do método `validate`.
