### ISSUE TITLE
validate_list

### ISSUE THREAD

**Issue by alvarofpp** [alvarofpp/validate-docbr#16]
Validar uma lista de documentos.

```python
from validate_docbr import CPF

cpf = CPF()

# Validar CPFs
cpf.validate_list(["012.345.678-90", "012.345.678-91"])  # [True, False]
```

**Comment by Jonatha-Varjao** [comment]
Eu poderia ajudar com isso alvaro, algum conselho em relação ao code-style, e aos requisitos que minha implementação precista ter ?

**Comment by alvarofpp** [comment]
Boa tarde, @Jonatha-Varjao.

O code-style seria o mais próximo do [PEP](https://www.python.org/dev/peps/pep-0008/). A implementação fica a seu critério, sendo que creio que a função iria executar o método `validate` da classe `n` vezes (`n` sendo o tamanho da lista passada). Como é um método mais geral, creio que seria ideal implementar na classe [`BaseDoc`](https://github.com/alvarofpp/validate-docbr/blob/master/validate_docbr/BaseDoc.py) e não em cada uma das classes de documentos, como é feito com o método `generate_list`.

Após isso, seria interessante documentar o método no [guia de uso](https://github.com/alvarofpp/validate-docbr/blob/master/docs/guia-de-uso.md).

**Comment by Jonatha-Varjao** [comment]
Basicamente na classe ABC vai ter o método da _validate_lista()_ onde meu objeto filho vai invocar o _validate()_ dele e adiciono os retornos na lista e retorno ela

é nesse caminho ?

```python
def validate_list(self, docs: List[str]) -> List[bool]:
        """Método para validar uma lista de documentos desejado."""
        bool_list = []
        
        for document in docs:
            bool_list.append(self.validate(document))
        
        return bool_list
```

**Comment by alvarofpp** [comment]
@Jonatha-Varjao 

`ABC` é a forma que o Python tem para dizer que é uma classe abstrata. O método (`validate_list`) estaria na classe `BaseDoc`. Dessa forma, como todas as classes de documentos herdam de `BaseDoc`, o fluxo que você sugeriu funcionaria perfeitamente.

Seu código está correto, sendo que eu recomendo usar [list comprehensions](https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions) por ser mais rápido que o `for` normal. O código ficaria:

```py
def validate_list(self, docs: List[str]) -> List[bool]:
    """Método para validar uma lista de documentos desejado."""
    return [ self.validate(doc) for doc in docs ]
```

**Comment by Jonatha-Varjao** [comment]
Optei pela list comprehension sim, vou fazer o pull request adicionando a função na classe e atualizando a documentação

vlw @alvarofpp
