### ISSUE TITLE
validate_docs

### ISSUE THREAD

**Issue by alvarofpp** [alvarofpp/validate-docbr#17]
Validar uma lista de tuplas de documentos.

A seguir, consta um jeito de como essa funcionalidade deve funcionar:
```python
from validate_docbr as docbr


# Documentos
documentos = [
    (docbr.CPF, "012.345.678-90"),
    (docbr.CNPJ, "01.234.567/8901-23"),
    (docbr.CPF, "01234567891"),
]

# Validar documentos
validacoes = docbr.validate_docs( documentos )
# Output
# [True, False, False]
```

**Comment by Jonatha-Varjao** [comment]
o primeiro índice da tupla é uma referência a um objeto herdado da BaseDoc ?
o pensamento que eu tive foi pegar essa referência e chamar seu respectivo método de validação passando o segundo índice da tupla.

**Comment by alvarofpp** [comment]
@Jonatha-Varjao 
Pode funcionar dessa forma que você está pensando. Também poderia ser uma constante que identificasse o documento, tipo `CPF = 1`, `CNPJ = 2` e por aí vai. Mas é só um exemplo, outro modo que poderia funcionar seria:

```py
documentos = [
    ('cpf', "012.345.678-90"),
    ('cnpj', "01.234.567/8901-23"),
    ('CPF', "01234567891"),
]
```

Passando uma string que ajudasse a identificar. No caso, `cpf` e `CPF` referenciariam o mesmo tipo de documento.

Sinta-se livre para sugerir e usar a abordagem que achar melhor.

**Comment by JoaoAPS** [comment]
Essa issue ainda está aberta? Eu gostaria de trabalhar nela se estiver.

**Comment by alvarofpp** [comment]
> Essa issue ainda está aberta? Eu gostaria de trabalhar nela se estiver.

Está aberta sim

**Comment by JoaoAPS** [comment]
Beleza, estou trabalhando nela então
