### ISSUE TITLE
Certidão de nascimento/casamento/óbito

### ISSUE THREAD

**Issue by alvarofpp** [alvarofpp/validate-docbr#27]
Usar como referência a biblioteca [geekcom/validator-docs](https://github.com/geekcom/validator-docs).

**Comment by claracavalcante** [comment]
Opa, ainda precisa?

**Comment by alvarofpp** [comment]
> Opa, ainda precisa?

Sim! 😊

**Comment by alvarofpp** [comment]
> Opa, ainda precisa?

Sim!

**Comment by claracavalcante** [comment]
Massa! Posso trabalhar nessa issue então?

**Comment by alvarofpp** [comment]
> Massa! Posso trabalhar nessa issue então?

Claro, sinta-se à vontade

**Comment by claracavalcante** [comment]
Oi, Alvaro! Feliz ano novo :)

Fiz essa validação de acordo com o [link](http://ghiorzi.org/DVnew.htm#zc) que tem na biblioteca indicada aqui. Estou com duas dúvidas.

O Número de Matrícula tem a configuração aaaaaa.bb.cc.dddd.e.fffff.ggg.hhhhhhh-ii, onde:
- aaaaaa indica o Código Nacional da Serventia (identificação única do cartório) ex.: 10453-9 (v. Nota final)
- dddd indica o Ano do Registro - ex.: 2013

A primeira dúvida é sobre o ano do registro. Você considera necessário restringir o ano? Exemplo, 2022 seria inválido já que ainda estamos em 2021.

A segunda dúvida é quanto a identificação única do cartório, que também tem um esquema de validação, já que o último algarismo é calculado a partir dos primeiros cinco.

Só a nível de comparação, a biblioteca [geekcom/validator-docs](geekcom/validator-docs) não faz nenhuma dessas duas validações (ano, identificação do cartório) para validar as certidões.

**Comment by alvarofpp** [comment]
Olá, Clara. Desculpa pela demora para responder (o ano começou corrido para mim). Feliz ano novo! (atrasado, mas o que vale é a intenção)

Primeira dúvida: creio que não precisa dessa validação. Existe o caso da equipe de desenvolvimento querer realizar diversos testes, podendo até fazer uso de geradores de documentos próprios, ou que queiram realizar uma validação diferente da nossa nos documentos deles, nesses casos a nossa restrição pode prejudicar o desenvolvimento deles. Inclusive seria interessante deixar isso claro na documentação da classe desse documento.

Segunda dúvida: creio ser muito essencial essa validação! Poderia ser primeiro verificado se a identificação única do cartório é válida para só depois validar todo o restante do documento. Algo que poderia ser implementado posteriormente (em uma outra issue) seria o uso de códigos ou classes para identificar em que ponto o documento é válido ou não. Nesse caso da segunda dúvida, seria um código que identificasse se a identificação única do cartório é inválida e outro para caso o restante seja inválido, porém sem restringir a possibilidade de retornar apenas um booleano.

**Comment by claracavalcante** [comment]
Olá, sem problemas! haha

1ª dúvida: Realmente faz sentido!

2ª dúvida: Concordo. É uma ótima ideia essa questão de validar o documento por partes. Há outros documentos além da Certidão que possuem essa característica também? De qualquer forma, se for possível criar a issue, eu poderia trabalhar nela também.

Em relação às duas dúvidas, você acredita que seria necessário documentar como caso especial no Guia de uso ou exemplificação sucinta nos comentários da própria classe Certidão seria suficiente?

**Comment by alvarofpp** [comment]
> Há outros documentos além da Certidão que possuem essa característica?

No geral os documentos possuem algumas validações além do digito verificador, como o [tamanho](https://github.com/alvarofpp/validate-docbr/blob/master/validate_docbr/CPF.py#L20) ou se tem [caracteres não permitidos](https://github.com/alvarofpp/validate-docbr/blob/master/validate_docbr/CPF.py#L15), o CPF possui uma [verificação extra que é nos casos especiais](https://github.com/alvarofpp/validate-docbr/blob/master/validate_docbr/CPF.py#L74).

> Em relação às duas dúvidas, você acredita que seria necessário documentar como caso especial no Guia de uso ou exemplificação sucinta nos comentários da própria classe Certidão seria suficiente?

Creio que para ambos os casos documentar no Guia de Uso já seja o suficiente.
