### ISSUE TITLE
Gerador de CNH às vezes gera documento inválido

### ISSUE THREAD

**Issue by JoaoAPS** [alvarofpp/validate-docbr#30]
Algumas vezes o método `CNH().generate()` retorna uma string com um traço (-) antes do último número,
por exemplo `1234567890-1`.
Assim, chamar `CNH().validate()` nesse número retorna falso.

Não sei as regras de geração de uma CNH, mas acredito que a presença do traço não esteja correta.
Acho que o problema está [nessa linha](https://github.com/alvarofpp/validate-docbr/blob/c841dbc5587e626e7e1ff31b56b3f02bb28b930d/validate_docbr/CNH.py#L59), que pode resultar em um número negativo.

**Comment by alvarofpp** [comment]
> Algumas vezes o método `CNH().generate()` retorna uma string com um traço (-) antes do último número,
> por exemplo `1234567890-1`.
> Assim, chamar `CNH().validate()` nesse número retorna falso.
> 
> Não sei as regras de geração de uma CNH, mas acredito que a presença do traço não esteja correta.
> Acho que o problema está [nessa linha](https://github.com/alvarofpp/validate-docbr/blob/c841dbc5587e626e7e1ff31b56b3f02bb28b930d/validate_docbr/CNH.py#L59), que pode resultar em um número negativo.

Creio que você identificou bem o problema, parabéns. Algo que pode resolver isso é a função [`abs`](https://docs.python.org/pt-br/3/library/functions.html#abs).

**Comment by JoaoAPS** [comment]
Na verdade, de acordo com [essa referência](https://www.devmedia.com.br/forum/validacao-do-numero-de-registro-de-cnh/354889) citada na issue original #6, a correção a fazer quando o último dígito verificador é negativo é somar 11 a ele.

Por coincidência, minha própria CNH é um dos casos em que o último dígito é negativo, e posso confirmar que somar 11 fornece o resultado certo, enquanto tirar o módulo não.

Se estiver de acordo, posso implementar a mudança.

**Comment by alvarofpp** [comment]
> Se estiver de acordo, posso implementar a mudança.

Estou de acordo, pode implementar!
