### ISSUE TITLE
Documentos inválidos passando como válidos na biblioteca

### ISSUE THREAD

**Issue by gabri14el** [alvarofpp/validate-docbr#33]
Oi, boa tarde. 

Segue exemplos de documentos que não deveriam ser dados como válidos, mas passam do mesmo jeito. 

`>>> import validate_docbr
>>> a = '7ebebce5c9537fa16a817caea2a79ca4'
>>> validate_docbr.CNS().validate(a)
>>> validate_docbr.CPF().validate("012.345.678-91")
False`

Eu tinha mais exemplos, porém era com meu próprio cpf e preferi não colocar, mas o exemplo era composto do meu cpf, sem pontos, mais uma letra a no final. Algo como _cpf_a

Até mais.

**Comment by alvarofpp** [comment]
Pelo que apurei, isso ocorre porque normalmente se tem uma limpeza do valor antes da validação (`doc = list(self._only_digits(doc))`, [CNS](https://github.com/alvarofpp/validate-docbr/blob/0dcc748e8301408b77619fc286d6edf3f812b2e0/validate_docbr/CNS.py#L14), [CPF](https://github.com/alvarofpp/validate-docbr/blob/0dcc748e8301408b77619fc286d6edf3f812b2e0/validate_docbr/CPF.py#L15)).

Como solução, creio que precisaria ser verificado se no valor existe algum `char` que não seja dígito e que não seja caractere de máscara (`.`, `-` e `/`).
