### ISSUE TITLE
Método mask da classe CNPJ não converte apropriadamente

### ISSUE THREAD

**Issue by giovani-dev** [alvarofpp/validate-docbr#37]
Estou utilizando essa biblioteca para fazer algumas validações no Django Rest Framework, entretanto quando quando eu adiciono um mascara em um CNPJ que já contem mascara, o retorno da função difere totalmente da formatação de um CNPJ com mascara.

![image](https://user-images.githubusercontent.com/64743075/124402199-20cfdb00-dd05-11eb-9193-e7b66bf544cb.png)

**Comment by ronaldokun** [comment]
> @leogregianin, não creio que ter essa opção a função `mask` seja coerente, visto que será realizado duas ações: limpeza da entrada e depois aplicação da máscara, porém apenas essa última corresponde ao nome da função. Mas se for uma demanda da comunidade, nada impede que possamos acrescentá-la ao pacote.
Faz sentido sim a função ter somente 1 propósito, no entanto ao receber um identificador já "mascarado", a função não deve alterar a entrada nesse caso.

Se receber uma entrada parcialmente mascarada, a função deve retornar o identificador mascarado corretamente. 

Para tal acho que faz sentido a função fazer uma das duas coisas internamente: verificar a validade da máscara ou limpar a entrada e aplicar a máscara. 

Ela retornar algo inválido para uma entrada já mascarada creio que se trata de um bug.
