### ISSUE TITLE
Sugestão: Mudanças nos métodos validate e mask

### ISSUE THREAD

**Issue by Eduardo-RFarias** [alvarofpp/validate-docbr#47]
Como discutido no pr #46  fiz algumas modificações na classe BaseDoc e nos métodos validate e mask da classe Cpf.
Gostaria que o código fosse revisado e, se estiver tudo certo, gostaria também de receber um feedback para que eu possa terminar de implementar nas outras classes.

Quero muito contribuir com essa biblioteca que eu achei bem útil.🥇 Muito obrigado desde já 😃 

# Mudanças
[Commit](https://github.com/Eduardo-RFarias/validate-docbr/commit/d4f0d469279fcece2daecbe14a49af42eba7aaf2)

- Foi adicionado um novo método e um construtor na classe BaseDoc
- O construtor da classe CPF agora define um regex_pattern que servirá para validar o cpf
- O método validate de CPF agora usa "check_formating()" em vez de "_validate_input()". (Houve uma pequena melhora no tempo de execução desse método)
- Um novo docstring foi criado para o método mask.

![image](https://user-images.githubusercontent.com/52677538/147299924-aa71b398-d0eb-4bb7-b748-b76309884a23.png)

**Comment by alvarofpp** [comment]
Sugestões gerais:
- Evite usar o `f` para formatação, pois quebra a compatibilidade do pacote com versões do Python menores que 3.6 (#24);
- Utilize nomes totalmente descritivos para as suas variáveis;
- Melhor que `== None` ou `!= None` é, respectivamente, `is None` e `is not None`.

> O construtor da classe CPF agora define um regex_pattern que servirá para validar o cpf

Faltou colocar o type hint de `custom_regex_pattern`. Creio que `custom_regex_pattern or r"""..."""` seria melhor se fosse um `if`. Não precisa comentar as partes do regex de CPF.

**Comment by Eduardo-RFarias** [comment]
### Fiz as modificações:
[Commit](https://github.com/Eduardo-RFarias/validate-docbr/commit/79d60742d26421c9b41c86c31c18d657ec78a0e2)

- Revisei também uma validação na classe BaseDoc pois parece que os argumentos de um construtor no python são opcionais. Usei um try except, dentro do método check_formatting, para garantir que o programador tenha passado um regex válido ao construtor da classe BaseDoc.
