### ISSUE TITLE
Falha ao validar CNPJ e CPF não formatados

### ISSUE THREAD

**Issue by brunotrbr** [alvarofpp/validate-docbr#49]
O CNPJ **00.000.000/0001-91** é o CNPJ do Banco do Brasil. Caso eu envie o CNPJ no formato **191**, o validador retorna que não é válido pois espera que sejam enviados os 14 caracteres.

Não tenho como consultar o CPF **191**, mas matematicamente é um CPF válido também, que o validador diz que não é válido por esperar os 11 caracteres.

**Comment by bruno-braganca** [comment]
Criei uma branch com a correção, mas não consigo fazer o Pull Request

**Comment by hub-lenf** [comment]
Basta você fazer isso manualmente:
```
import re

from validate_docbr import CNPJ


def validate_cnpj(your_value):
    """Validate CNPJ document."""

    expected_length = 14
    treated_value = re.sub("[^0-9]", "", your_value).zfill(expected_length)

    cnpj_validator = CNPJ()
    return cnpj_validator.validate(treated_value)

print(validate_cnpj(your_value="00.000.000/0001-91"))
print(validate_cnpj(your_value="191"))
```
