### ISSUE TITLE
Validação de CNH

### ISSUE THREAD

**Issue by alvarofpp** [alvarofpp/validate-docbr#6]
# Implementar a validação de CNH
Carteira Nacional de Habilitação.

## Descrição
A Carteira Nacional de Habilitação, também conhecida como carteira de motorista ou carteira de habilitação é o nome dado ao documento oficial que, no Brasil, atesta a aptidão de um cidadão para conduzir veículos automotores terrestres. Portanto, seu porte é obrigatório ao condutor de qualquer veículo desse tipo.

## Algoritmo de validação
Abaixo encontra-se alguns links que podem ajudar a entender o algoritmo de validação do CNH.
- [DevMedia - Validação do número de registro de CNH](https://www.devmedia.com.br/forum/validacao-do-numero-de-registro-de-cnh/354889)
- [danielsouza/validarCNH](https://github.com/danielsouza/validarCNH)
- [Código Fonte - Validação de CNH](https://www.codigofonte.com.br/codigos/validacao-de-cnh)

**Comment by luizpericolo** [comment]
Eu gostaria de trabalhar nesse issue. Você tem idéia de como quer estruturar as classes?

**Comment by alvarofpp** [comment]
Boa noite, @luizpericolo.

É interessante que a classe usada para CNH siga o padrão estabelecido nas outras classes, ou seja, herdar diretamente da classe [`BaseDoc`](https://github.com/alvarofpp/validate-docbr/blob/master/validate_docbr/BaseDoc.py). Isso implica que 3 métodos sejam implementados:
- `validate`: validar o documento passado;
- `generate`: gerar um documento válido, no caso seria gerar um CNH válido;
- `mask`: mascara o documento passado. Exemplo de CPF: entra `01234567890`, sai `012.345.678-90`.

O nome da classe pode ser `CNH`.
Sinta-se a vontade para implementar "métodos privados" na classe que te ajudem na implementação do todo. Por exemplo, eu criei os métodos `_generate_first_digit` e `_generate_second_digit` na classe CPF para me ajudarem na geração dos dígitos verificados, visto que uso isso em mais de uma parte da classe.

**Comment by luizpericolo** [comment]
Perfeito @alvarofpp, obrigado pelo norte. Assim que tiver algo mais substancial eu abro um draft PR pra gente discutir mais.

**Comment by luizpericolo** [comment]
@alvarofpp  Me enrolei com outras contribuições do hacktoberfest e prefiro deixar essa para outra pessoa que se interessar. Valeu!
