### ISSUE TITLE
Validação de Título Eleitoral

### ISSUE THREAD

**Issue by alvarofpp** [alvarofpp/validate-docbr#7]
# Implementar a validação de Título Eleitoral
Título de eleitor.

## Descrição
Título de eleitor é o documento que comprova que um determinado cidadão está inscrito na Justiça Eleitoral do Brasil e se encontra apto a exercer tanto o eleitorado ativo (votar num candidato), quanto o eleitorado passivo (ser votado como candidato) em eleições municipais, estaduais e federais, excetuando-se, no caso do eleitorado passivo os cidadãos que se encaixem no artigo 1° da lei complementar n° 64 de 18 de maio de 1990.

## Algoritmo de validação
Abaixo encontra-se alguns links que podem ajudar a entender o algoritmo de validação do CNH.
- [Wikipedia - Cálculo do dígito verificador](https://pt.wikipedia.org/wiki/T%C3%ADtulo_eleitoral#C%C3%A1lculo_do_d%C3%ADgito_verificador)

**Comment by luizpericolo** [comment]
Eu gostaria de trabalhar nesse issue. Você tem idéia de como quer estruturar as classes?

**Comment by alvarofpp** [comment]
Boa noite, @luizpericolo.

É interessante que a classe usada para Título Eleitoral siga o padrão estabelecido nas outras classes, ou seja, herdar diretamente da classe [`BaseDoc`](https://github.com/alvarofpp/validate-docbr/blob/master/validate_docbr/BaseDoc.py). Isso implica que 3 métodos sejam implementados:
- `validate`: validar o documento passado;
- `generate`: gerar um documento válido, no caso seria gerar um título eleitoral válido;
- `mask`: mascara o documento passado. Exemplo de CPF: entra `01234567890`, sai `012.345.678-90`.

O nome da classe pode ser `TituloEleitoral`.

**Comment by luizpericolo** [comment]
@alvarofpp 
Criei um draft PR pra pegar um feedback seu. Coloquei mais itens na seção TODO do PR. Se estiver algo faltando pode comentar lá.
